### ISSUE TITLE
Support horizontal scroll (notebook touchpad), clickable arrows, abitrary slide contents (non-images)

### ISSUE THREAD

**Issue by inoas** [bushblade/Full-Screen-Touch-Slider#1]
1. Would you be OK to add any GPL or MIT based license?
2. For above see https://github.com/inoas/Full-Screen-Touch-Slider/tree/enhanced

**Comment by bushblade** [comment]
Hi inoas.
Thanks for the issue.
It should already work on notebooks and tablets, can you explain what issue you are having exactly please?
This project was just a prototype for a React component which I [published here](https://www.npmjs.com/package/react-touch-drag-slider).
In which it is currently possible to pass any React node as a child to the slider, it doesn't have to be an image.
The slider doesn't have arrows by default, as I wanted it free to add in your own arrows or buttons as you need. The React component provides functionality to do that.

**Comment by inoas** [comment]
Hello @bushblade,

first of all, would a license be okay, so I can use it elsewhere? I will just merge the upstream license to my fork.

Then, on my macbook I use two fingers swipe to do a horizontal scroll (like a 4 ways mousewheel, which do exist) ... and that didn't work for me.

Also, the buttons are optional, just not include them in html and the feature is not there.

And, I am not saying you should merge this, I am just giving feedback and sharing back - you saved me from having to write it from scratch entirely AND not having to use a ready made solution that would probably be far to large.

And last, I am not using react (I don't mind React, but I am more inclined to use Svelte/TS or in future [Gleam](https://gleam.run/) to create web apps - Gleam is statically typed, functional ML style, but low barrier and clear syntax and transpiles down to Erlang/BEAM and JS). So I cannot test the react component as of now.

So thank you again for sharing this!

**Comment by bushblade** [comment]
Thanks for the feedback, I added a licence.
